### ISSUE TITLE
GCPhone doesn't regognice calls from other Players

### ISSUE THREAD

**Issue by ghost** [Re-Ignited-Development/Re-Ignited-Phone#153]
So i downloaded the recource 1.2 and i could start the phone and use twitter, but if i call anyone, they don't get my call. Could someone please help me?

**Comment by Adrianmcmastergaming** [comment]
> So i downloaded the recource 1.2 and i could start the phone and use twitter, but if i call anyone, they don't get my call. Could someone please help me?

Did you start the gcphone after es_extended and before all other scripts? I had same problem but fixed it in theend

**Comment by darektion** [comment]
I am also getting the same issue.

_I started the resources in this order:_
start mapmanager
start chat
start spawnmanager
start sessionmanager
start basic-gamemode
start fivem
start hardcap
start rconlog
start scoreboard
set mysql_connection_string "server=XXX;"
ensure mysql-async
ensure mysql
ensure async
ensure cron
ensure esx_skin
ensure esx_identity
ensure es_extended
**ensure gcphone**
ensure screenshot-basic
...

**Comment by Rajhab** [comment]
> 
> 
> > So i downloaded the recource 1.2 and i could start the phone and use twitter, but if i call anyone, they don't get my call. Could someone please help me?
> 
> Did you start the gcphone after es_extended and before all other scripts? I had same problem but fixed it in theend

Yes i did it after es_extended and before the jobs

Could you please help me?

**Comment by Adrianmcmastergaming** [comment]
If you got mumble voip go and open the cnfig.lua and make sure you have this.
externalAddress = "127.0.0.1",
externalPort = 30130,

callChannelNames = { -- Add named call channels (Defaults to [channel number])
	[0] = "Default Phone Channel 0",
],

Then open your server.cfg and enter this
# Mumble Voip
setr voice_use3dAudio true
setr voice_useSendingRangeOnly true

I got the phone working in the end and you hear music.
Almost for. Make sure you have phone in you inventory because even though you press f1 and its there for some reason you cannot call until you have a phone in your inventory.
make sure you have admin control.   In chat enter /giveitem  id number of person  phone 1
You will need to do this for yourself if there is no phone.  I think it has something to do with part of the script for when you have to buy a phone when some setting are set to true in the config.  It took me a week to solve the problem. When a person calls you you will hear music playing and you press F1 to open your phone except the call and you hear the other person.
I did a video that might help you and others. https://www.youtube.com/watch?v=y_iCjccyIdw&t=165s
